### ISSUE TITLE
[Datafusion] - Support joins on Float32/Float64 columns

### ISSUE THREAD

**Issue by francis-du** [apache/arrow-datafusion#1053]
**Describe the bug**

When I joins on Float32/Float64 columns, there is a issue:

```sql
> select * from public.simple as a join (select * from public.simple as b) on a.c1=b.c1;
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Unsupported data type in hasher")', datafusion/src/physical_plan/hash_join.rs:583:14
0 rows in set. Query took 0.034 seconds.
```

table info:

```sql
> show columns from public.simple;
+---------------+--------------+------------+-------------+-----------+-------------+
| table_catalog | table_schema | table_name | column_name | data_type | is_nullable |
+---------------+--------------+------------+-------------+-----------+-------------+
| datafusion    | public       | simple     | c1          | Float64   | NO          |
| datafusion    | public       | simple     | c2          | Float64   | NO          |
| datafusion    | public       | simple     | c3          | Boolean   | NO          |
+---------------+--------------+------------+-------------+-----------+-------------+
```

There is also this similar issue #187, These issues is caused by hash join `equal rows` not support Float32/Float64 datatypes. I will fix this.

https://github.com/apache/arrow-datafusion/blob/26399ed2405dcacd505f4af73c5ecf608cb6aa9d/datafusion/src/physical_plan/hash_join.rs#L759-L796

**Comment by houqp** [comment]
Thanks @francis-du , I have assigned the issue to you :)

**Comment by francis-du** [comment]
OK, Thanks~
