### ISSUE TITLE
Panic while running join datatypes/schema.rs:165:10

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#601]
**Describe the bug**

> select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/datatypes/schema.rs:165:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**To Reproduce**
```shell
echo "1" > /tmp/foo.csv
cargo run -p datafusion-cli 
```

```sql
> CREATE EXTERNAL TABLE foo(bar int)
STORED AS CSV
LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0.000 seconds.
> select * from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/datatypes/schema.rs:165:10
```

**Expected behavior**
Expected output of 1 row, with columns `f1.foo` and `f2.foo` each with value 1

**Additional context**
Likely follow on work from https://github.com/apache/arrow-datafusion/pull/55

**Comment by alamb** [comment]
Interestingly, it seems like f2.bar is causing some issues:

```
> select f1.bar from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
+-----+
| bar |
+-----+
| 1   |
+-----+
1 row in set. Query took 0.020 seconds.
> select f1.bar, f2.bar from foo as f1 JOIN foo as f2 ON f1.bar = f2.bar;
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/datatypes/schema.rs:165:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
