### ISSUE TITLE
```

### ISSUE THREAD

**Issue by Tracyca209** [apache/arrow-datafusion#6484]
```
(platformdirs-env) tw@mba2020 platformdirs %  uname -a
Darwin mba2020.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64

(platformdirs-env) tw@mba2020 platformdirs % tox -e fix                                             
fix: commands[0]> pre-commit run --all-files --show-diff-on-failure
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/tw/.cache/pre-commit/repom2zu8hji/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/tw/.cache/pre-commit/repom2zu8hji
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/Users/tw/.cache/pre-commit/repom2zu8hji/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/Users/tw/.cache/pre-commit/repom2zu8hji/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/Users/tw/.cache/pre-commit/repom2zu8hji/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/private/var/folders/61/qtqwzmxd7t1fb19zck5k3q0h0000gn/T/pip-build-env-nytdzqml/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/private/var/folders/61/qtqwzmxd7t1fb19zck5k3q0h0000gn/T/pip-build-env-nytdzqml/overlay/lib/python3.9/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /Users/tw/.cache/pre-commit/pre-commit.log
fix: exit 3 (3.31 seconds) /Users/tw/w/platformdirs> pre-commit run --all-files --show-diff-on-failure pid=25879
  fix: FAIL code 3 (3.36=setup[0.05]+cmd[3.31] seconds)
  evaluation failed :( (3.54 seconds)
```

_Originally posted by @ThomasWaldmann in https://github.com/platformdirs/platformdirs/issues/133_

**Comment by waynexia** [comment]
Looks like unrelated. Feel free to reopen it if I have overlooked anything.
