### ISSUE TITLE
Ballista integration tests broken due to metrics issue

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#940]
**Describe the bug**

Executor crashed with:
```
thread 'tokio-runtime-worker' panicked at 'Mismatched metric types. Can not aggregate Count { name: "output_rows", count: Count { value: 46 } } with value OutputRows(Count { value: 74124 })', datafusion/src/physical_plan/metrics/value.rs:239:17
stack backtrace:
   0:     0x558cec89d230 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x558cec89d230 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558cec89d230 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558cec89d230 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558cec8c11ac - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x558cec897405 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x558cec89f88b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558cec89f88b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558cec89f88b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x558cec89f361 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x558cec89ff54 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x558cec89fa37 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x558cec89d72c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558cec89f999 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x558ceb99701b - std::panicking::begin_panic_fmt::h5479575e112541f8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:     0x558cec041dda - datafusion::physical_plan::metrics::value::MetricValue::add::h48a14ca40c6a9723
  16:     0x558cec15014e - datafusion::physical_plan::metrics::MetricsSet::aggregate_by_partition::h6bc9a339c7056ad6
  17:     0x558cebe21f9a - <datafusion::physical_plan::display::IndentVisitor as datafusion::physical_plan::ExecutionPlanVisitor>::pre_visit::hcb024794c49cf04c
  18:     0x558cebe20ac6 - datafusion::physical_plan::visit_execution_plan::hb9cca072d849ca9d
  19:     0x558cebe20b55 - datafusion::physical_plan::visit_execution_plan::hb9cca072d849ca9d
  20:     0x558cebe21cb4 - <datafusion::physical_plan::display::DisplayableExecutionPlan::indent::Wrapper as core::fmt::Display>::fmt::hb7233ce15b521934
  21:     0x558cebbb853a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdc6845fa2c2699d2
  22:     0x558cebaad46b - tokio::runtime::task::core::CoreStage<T>::poll::hdf84ea0f2fd1fa1c
  23:     0x558cebb174d7 - tokio::runtime::task::harness::Harness<T,S>::poll::h676c0b25ff088550
  24:     0x558cec53961f - std::thread::local::LocalKey<T>::with::h79472cd3ec15aff6
  25:     0x558cec540a17 - tokio::runtime::thread_pool::worker::Context::run_task::h4905b61a80bac508
  26:     0x558cec53f959 - tokio::runtime::thread_pool::worker::Context::run::hf6026866c1eb65d7
  27:     0x558cec52b163 - tokio::macros::scoped_tls::ScopedKey<T>::set::hc2542d2d64a3f97d
  28:     0x558cec53f341 - tokio::runtime::thread_pool::worker::run::hbc6c8cb7b89bb303
  29:     0x558cec528f01 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h06830857576d411d
  30:     0x558cec527258 - tokio::runtime::task::harness::Harness<T,S>::poll::hb7853802682c95c4
  31:     0x558cec524ca1 - tokio::runtime::blocking::pool::Inner::run::h6e93b40e6120732a
  32:     0x558cec533f9b - std::sys_common::backtrace::__rust_begin_short_backtrace::h548f72dc6eff47de
  33:     0x558cec529c28 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haf9457c9eded3fdc
  34:     0x558cec8a3dd7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7ece6cfefaff1005
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  35:     0x558cec8a3dd7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb8b48e55c21f193e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  36:     0x558cec8a3dd7 - std::sys::unix::thread::Thread::new::thread_start::h8c7c4450dba62914
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  37:     0x7f9cde10dfa3 - start_thread
  38:     0x7f9cddeb64cf - clone
  39:                0x0 - <unknown>
```

**To Reproduce**
`./dev/integration-tests.sh`

**Comment by andygrove** [comment]
@alamb fyi

**Comment by alamb** [comment]
I will fix this
