### ISSUE TITLE
`generate_series` and `range` panic on edge cases

### ISSUE THREAD

**Issue by jonahgao** [apache/arrow-datafusion#9499]
### Describe the bug

These functions will panic when the parameters are boundary values such as `i64::MIN` and `i64::MAX`.

### To Reproduce

```sh
DataFusion CLI v36.0.0
❯ select range(1, -1, -9223372036854775808);
thread 'main' panicked at datafusion/functions-array/src/kernels.rs:304:63:
attempt to negate with overflow
```

```sh
❯ select generate_series(9223372036854775807, 9223372036854775807);
thread 'main' panicked at datafusion/functions-array/src/kernels.rs:307:13:
attempt to add with overflow
```

### Expected behavior

Avoid panic.

**Comment by jonahgao** [comment]
take

**Comment by Lordworms** [comment]
Thank you
